# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大统计与数据科学联合会议
email: contact@cos.name
description: 第七届中国人民大学国际统计论坛/第九届中国R语言会议/2016百分点数据与价值论坛
baseurl: "/stat2016" # the subpath of your site, e.g. /blog
url: "http://stat2016.china-r.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
